
 spring:
   data:
     elasticsearch:
       properties:
         node.name: fii-client
         # set to false when running standalone ES server
         node.master: true
         # set to false when running standalone ES server
         node.data: true
       #cluster-nodes: 192.168.56.53:9300
 logging:
   level:
     ROOT: INFO
     org.elasticsearch.bootstrap: ERROR
     fii.practic: DEBUG
 server:
   port: 9720
